** Linux Build Steps
This assumes available Netgen/NGSolve

#+BEGIN_SRC shell
git clone https://gitlab.asc.tuwien.ac.at/jschoeberl/xfem.git
cd xfem
mkdir build
cd build
cmake ../ -DINSTALL_DIR=INSTLOCATION && make && make install
#+END_SRC

for the INSTLOCATION please choose the Netgen/NGSolve location. 
Otherwise make sure that the installed xfem-libraries will be found by python

** Examples
To run the python examples be sure to follow the build steps above.
Then navigate into the =py_tutorials= or =stokes/py_demos= or =tracefem/py_demos= and run
#+BEGIN_SRC shell
netgen example.py
#+END_SRC
where =example.py= stands for any of the available python files.

** Testing
Tests are enabled by default.
To run the test navigate to the build directory and run =make test=
or =ctest=.
If you need to see specific tests failing use =ctest -V=.
To run individual tests use =ctest -R <regex>=. E.g. =ctest -R h1= to only run h1 integration
tests.

** pde vs. py files
pde-files only still exists for backward compatibility. 
python-files are the new standard.
